<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>uhara10</AssemblyName>
    <TargetFramework>net4.8.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>

    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../lib/LiveSplit/src/LiveSplit.Core/LiveSplit.Core.csproj" />
    <ProjectReference Include="../lib/LiveSplit/src/LiveSplit.View/LiveSplit.View.csproj" />
    <ProjectReference Include="../lib/LiveSplit/components/LiveSplit.ScriptableAutoSplit/src/LiveSplit.ScriptableAutoSplit/LiveSplit.ScriptableAutoSplit.csproj" />
    <ProjectReference Include="../lib/LiveSplit/src/UpdateManager/UpdateManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />

    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.45" />
    <PackageReference Include="SharpDisasm" Version="1.1.11" />
  </ItemGroup>

  <Target Name="MergeAssemblies" AfterTargets="AfterBuild">
    <PropertyGroup>
      <LsPath Condition="'$(LsPath)' != ''">$(LsPath)/Components</LsPath>
      <LsPath Condition="'$(LsPath)' == ''">$(OutputPath)</LsPath>
    </PropertyGroup>

    <ItemGroup>
      <AssembliesToMerge Include="$(OutputPath)/SharpDisAsm.dll" />
      <AssembliesToMerge Include="$(OutputPath)/$(AssemblyName).dll" />
    </ItemGroup>

    <ILRepack
      TargetKind="Dll"
      LibraryPath="$(OutputPath)"
      InputAssemblies="@(AssembliesToMerge)"
      OutputFile="$(LsPath)/$(AssemblyName)" />
  </Target>

</Project>
